title: EZEQUIEL RIVERO # your name (or website title) here
logo: "/images/cover_6_light.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Cancer Researcher turned Data Scientist with 10+ years experience. Skilled in data cleaning, statistical analysis, and extracting insights. Currently expanding my skillset in machine learning. Proficient in R and Python. 
  <br><br>
  Passionate about data-driven solutions in healthcare and sustainability. Love problem-solving, nature, and sports. Let's connect on LinkedIn!
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


