title: Ezequiel Rivero # your name (or website title) here
logo: "/images/image1-0.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  With a PhD in cancer research, I transitioned into data science, driven by a passion for uncovering patterns and solving problems. With 5+ years of experience in data cleaning, statistical analysis, and extracting insights, I am expanding my knowledge in machine learning.
  <br><br>
  Proficient in R and Python, I am dedicated to driving impactful data-driven decisions, particularly in healthcare and sustainable sectors. Feel free to connect with me on LinkedIn.
  <br><br>
  <a href="https://www.linkedin.com/in/ezequielmrivero/" class="icon-link">
    <img src="/images/linkedin.svg" alt="LinkedIn Profile" style="width:32px; height:32px;">
  </a>
  <a href="https://github.com/ezemriv" class="icon-link">
    <img src="/images/github.svg" alt="GitHub Profile" style="width:32px; height:32px;">
  </a>
  <a href="https://scholar.google.com/citations?user=Bg4eGzkAAAAJ&hl=en" class="icon-link">
    <img src="/images/publications.svg" alt="Google Scholar Publications" style="width:32px; height:32px;">
  </a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
