title: Ezequiel M Rivero, PhD # your name (or website title) here
logo: "/images/logo1_nobg.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With a PhD and a strong background in cancer research, I have transitioned into the field of data science, driven by a passion for uncovering hidden patterns and solving problems. Leveraging over 5 years of experience in data cleaning, statistical analysis, and extracting actionable insights, I am now focusing on expanding my knowledge in machine learning. Proficient in R and Python, I am dedicated to applying my skills to drive impactful data-driven decisions. I am particularly interested in applying my expertise in the healthcare or sustainable sectors. 
  <br><br>
  Feel free to connect with me on LinkedIn. 
  <br><br>
  <a href="https://www.linkedin.com/in/ezequielmrivero/">My LinkedIn Profile</a>
  <a href="https://www.linkedin.com/in/ezequielmrivero/">My publications</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
